In [1]:
import csv
import numpy as np
import torch

In [2]:
wine_path = "/Users/mnctty/Desktop/DL with Pytorch/data/winequality-white.csv" 

In [3]:
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";",skiprows=1)
wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [4]:
col_list = next(csv.reader(open(wine_path), delimiter=';'))

In [5]:
csv.reader(open(wine_path), delimiter=';')

In [6]:
col_list

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality']

In [7]:
wineq_numpy.shape, col_list

((4898, 12),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

In [8]:
len(col_list)

12

### датасет

In [22]:
wineq = torch.from_numpy(wineq_numpy)
wineq.shape, wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [23]:
data = wineq[:, :-1]
target = wineq[:,-1]
data.shape, target.shape

(torch.Size([4898, 11]), torch.Size([4898]))

In [24]:
target

tensor([6., 6., 6.,  ..., 6., 7., 6.])

#### есть два вида: в инт и ванхот энкодинг

In [25]:
target.long()

tensor([6, 6, 6,  ..., 6, 7, 6])

In [26]:
target_onehot = torch.zeros(target.shape[0], 10)
target_onehot

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [47]:
# target_onehot.storage()

In [48]:
target_onehot.shape

torch.Size([4898, 10])

In [49]:
target_index = target.unsqueeze(1)
# target_index = torch.zeros(target.shape[0], 10)

In [55]:
target_index.dtype(torch.int16)

TypeError: 'torch.dtype' object is not callable

In [51]:
target_index.max()

tensor(9.)

In [52]:
target_index.long()

tensor([[6],
        [6],
        [6],
        ...,
        [6],
        [7],
        [6]])

In [54]:
target_index = int(target_index)

ValueError: only one element tensors can be converted to Python scalars

In [53]:
target_index.storage()

 7.0
 0.27000001072883606
 0.36000001430511475
 20.700000762939453
 0.04500000178813934
 45.0
 170.0
 1.0010000467300415
 3.0
 0.44999998807907104
 8.800000190734863
 6.0
 6.300000190734863
 0.30000001192092896
 0.3400000035762787
 1.600000023841858
 0.04899999871850014
 14.0
 132.0
 0.9940000176429749
 3.299999952316284
 0.49000000953674316
 9.5
 6.0
 8.100000381469727
 0.2800000011920929
 0.4000000059604645
 6.900000095367432
 0.05000000074505806
 30.0
 97.0
 0.9951000213623047
 3.259999990463257
 0.4399999976158142
 10.100000381469727
 6.0
 7.199999809265137
 0.23000000417232513
 0.3199999928474426
 8.5
 0.057999998331069946
 47.0
 186.0
 0.9955999851226807
 3.190000057220459
 0.4000000059604645
 9.899999618530273
 6.0
 7.199999809265137
 0.23000000417232513
 0.3199999928474426
 8.5
 0.057999998331069946
 47.0
 186.0
 0.9955999851226807
 3.190000057220459
 0.4000000059604645
 9.899999618530273
 6.0
 8.100000381469727
 0.2800000011920929
 0.4000000059604645
 6.900000095367432
 0.0500

In [39]:
target_index.shape

torch.Size([4898, 1])

In [40]:
target_index

tensor([[6.],
        [6.],
        [6.],
        ...,
        [6.],
        [7.],
        [6.]])

In [41]:
target_onehot.scatter_(1, target_index, 1.0)

RuntimeError: index 4668431376536567808 is out of bounds for dimension 1 with size 10

In [56]:
bad_indexes = target <= 3

In [57]:
bad_indexes

tensor([False, False, False,  ..., False, False, False])