In [7]:
import imageio
import torch

In [45]:
batch_size = 3
batch = torch.zeros(batch_size, 3, 630, 1024, dtype=torch.uint8)

In [46]:
img_arr = imageio.imread('/Users/mnctty/Desktop/DL with Pytorch/1_lessons/horses.jpeg') 

In [47]:
img_arr.shape

(630, 1024, 3)

In [48]:
img = torch.from_numpy(img_arr)

In [49]:
out = img.permute(2, 0, 1)

In [50]:
out.shape

torch.Size([3, 630, 1024])

In [51]:
out = out[:3]

In [52]:
out.shape

torch.Size([3, 630, 1024])

In [53]:
out

tensor([[[221, 220, 221,  ...,  43,  44,  46],
         [219, 219, 220,  ...,  47,  45,  46],
         [221, 220, 220,  ...,  47,  48,  49],
         ...,
         [ 74,  71,  78,  ...,  69,  59,  52],
         [ 61,  72,  83,  ...,  68,  57,  46],
         [ 74,  88,  97,  ...,  60,  59,  45]],

        [[191, 190, 190,  ...,  47,  48,  49],
         [189, 188, 189,  ...,  49,  47,  48],
         [190, 189, 191,  ...,  50,  49,  50],
         ...,
         [105, 103, 107,  ...,  86,  79,  68],
         [ 93,  99, 105,  ...,  84,  73,  61],
         [106, 113, 116,  ...,  79,  75,  59]],

        [[157, 156, 159,  ...,  32,  34,  40],
         [155, 157, 158,  ...,  35,  33,  35],
         [159, 158, 159,  ...,  33,  33,  34],
         ...,
         [ 12,   4,   1,  ...,  15,  10,   5],
         [  0,   2,   7,  ...,  19,   8,   0],
         [  5,  19,  26,  ...,  15,  12,   0]]], dtype=torch.uint8)

In [54]:
i = 1

In [55]:
batch[i] = out

In [56]:
batch[0] = out

In [58]:
batch[2] = out

In [59]:
batch.shape

torch.Size([3, 3, 630, 1024])

In [61]:
batch

tensor([[[[221, 220, 221,  ...,  43,  44,  46],
          [219, 219, 220,  ...,  47,  45,  46],
          [221, 220, 220,  ...,  47,  48,  49],
          ...,
          [ 74,  71,  78,  ...,  69,  59,  52],
          [ 61,  72,  83,  ...,  68,  57,  46],
          [ 74,  88,  97,  ...,  60,  59,  45]],

         [[191, 190, 190,  ...,  47,  48,  49],
          [189, 188, 189,  ...,  49,  47,  48],
          [190, 189, 191,  ...,  50,  49,  50],
          ...,
          [105, 103, 107,  ...,  86,  79,  68],
          [ 93,  99, 105,  ...,  84,  73,  61],
          [106, 113, 116,  ...,  79,  75,  59]],

         [[157, 156, 159,  ...,  32,  34,  40],
          [155, 157, 158,  ...,  35,  33,  35],
          [159, 158, 159,  ...,  33,  33,  34],
          ...,
          [ 12,   4,   1,  ...,  15,  10,   5],
          [  0,   2,   7,  ...,  19,   8,   0],
          [  5,  19,  26,  ...,  15,  12,   0]]],


        [[[221, 220, 221,  ...,  43,  44,  46],
          [219, 219, 220,  ...,  47

## нормализация

In [62]:
batch.float()

tensor([[[[221., 220., 221.,  ...,  43.,  44.,  46.],
          [219., 219., 220.,  ...,  47.,  45.,  46.],
          [221., 220., 220.,  ...,  47.,  48.,  49.],
          ...,
          [ 74.,  71.,  78.,  ...,  69.,  59.,  52.],
          [ 61.,  72.,  83.,  ...,  68.,  57.,  46.],
          [ 74.,  88.,  97.,  ...,  60.,  59.,  45.]],

         [[191., 190., 190.,  ...,  47.,  48.,  49.],
          [189., 188., 189.,  ...,  49.,  47.,  48.],
          [190., 189., 191.,  ...,  50.,  49.,  50.],
          ...,
          [105., 103., 107.,  ...,  86.,  79.,  68.],
          [ 93.,  99., 105.,  ...,  84.,  73.,  61.],
          [106., 113., 116.,  ...,  79.,  75.,  59.]],

         [[157., 156., 159.,  ...,  32.,  34.,  40.],
          [155., 157., 158.,  ...,  35.,  33.,  35.],
          [159., 158., 159.,  ...,  33.,  33.,  34.],
          ...,
          [ 12.,   4.,   1.,  ...,  15.,  10.,   5.],
          [  0.,   2.,   7.,  ...,  19.,   8.,   0.],
          [  5.,  19.,  26.,  ...

In [63]:
batch = batch/255.

In [64]:
batch

tensor([[[[0.8667, 0.8627, 0.8667,  ..., 0.1686, 0.1725, 0.1804],
          [0.8588, 0.8588, 0.8627,  ..., 0.1843, 0.1765, 0.1804],
          [0.8667, 0.8627, 0.8627,  ..., 0.1843, 0.1882, 0.1922],
          ...,
          [0.2902, 0.2784, 0.3059,  ..., 0.2706, 0.2314, 0.2039],
          [0.2392, 0.2824, 0.3255,  ..., 0.2667, 0.2235, 0.1804],
          [0.2902, 0.3451, 0.3804,  ..., 0.2353, 0.2314, 0.1765]],

         [[0.7490, 0.7451, 0.7451,  ..., 0.1843, 0.1882, 0.1922],
          [0.7412, 0.7373, 0.7412,  ..., 0.1922, 0.1843, 0.1882],
          [0.7451, 0.7412, 0.7490,  ..., 0.1961, 0.1922, 0.1961],
          ...,
          [0.4118, 0.4039, 0.4196,  ..., 0.3373, 0.3098, 0.2667],
          [0.3647, 0.3882, 0.4118,  ..., 0.3294, 0.2863, 0.2392],
          [0.4157, 0.4431, 0.4549,  ..., 0.3098, 0.2941, 0.2314]],

         [[0.6157, 0.6118, 0.6235,  ..., 0.1255, 0.1333, 0.1569],
          [0.6078, 0.6157, 0.6196,  ..., 0.1373, 0.1294, 0.1373],
          [0.6235, 0.6196, 0.6235,  ..., 0

In [65]:
n_channels = batch.shape[1] 
for c in range(n_channels):
    mean = torch.mean(batch[:, c])
    std = torch.std(batch[:, c])
    batch[:, c] = (batch[:, c] - mean) / std

## 3d images

In [66]:
# 3d images are mri and ct images, e.g.


# add new a dimention Depth - leading to a 5D tensor of shape N × C × D × H × W.

In [67]:
import imageio

In [72]:
dir_path = "/Users/mnctty/Downloads/28_09_2019__TH_SpineContr_3Tsl/DCM/" 
vol_arr = imageio.volread(dir_path, 'DICOM')
vol_arr.shape

Reading DICOM (examining files): 1/659 files (0.231/659 files (4.7%67/659 files (10.2101/659 files (15.3%123/659 files (18.7%153/659 files (23.2%187/659 files (28.4%223/659 files (33.8%256/659 files (38.8%293/659 files (44.5%329/659 files (49.9%362/659 files (54.9%398/659 files (60.4%436/659 files (66.2%472/659 files (71.6%504/659 files (76.5%537/659 files (81.5%570/659 files (86.5%603/659 files (91.5%641/659 files (97.3%659/659 files (100.0%)
  Found 14 correct series.
Reading DICOM (loading data): 8/8  (100.0%)


(8, 512, 512)

In [71]:
type(vol_arr)

imageio.core.util.Array

In [76]:
import numpy as np

In [79]:
# добавила .astype(np.float64)

# иначе была ошибка TypeError: 
# can't convert np.ndarray of type numpy.uint16. 
# The only supported types are: float64, float32, float16, int64, 
# int32, int16, int8, uint8, and bool.

In [80]:
vol = torch.from_numpy(vol_arr.astype(np.float64)).float()

In [81]:
vol = torch.unsqueeze(vol, 0)
vol.shape

torch.Size([1, 8, 512, 512])

In [82]:
vol = torch.unsqueeze(vol, 0)
# vol = torch.squeeze(vol, 0)

In [86]:
vol.shape

torch.Size([1, 8, 512, 512])