In [1]:
import torch

In [2]:
a = torch.ones(5)

In [3]:
a

tensor([1., 1., 1., 1., 1.])

In [4]:
a[1]

tensor(1.)

In [6]:
float(a[1])

1.0

In [7]:
a[1] = float(a[1])

In [9]:
a[1] = 2

In [10]:
a

tensor([1., 2., 1., 1., 1.])

In [29]:
l = list(range(9))

In [30]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [31]:
a = torch.FloatTensor(l)

In [32]:
a

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [33]:
a.shape

torch.Size([9])

In [41]:
a.storage()

 0.0
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
 7.0
 8.0
[torch.FloatStorage of size 9]

In [44]:
a.storage_offset()

0

In [45]:
a.size()

torch.Size([9])

In [48]:
a.storage().size()

9

In [51]:
a.shape

torch.Size([9])

In [58]:
a.stide

AttributeError: 'Tensor' object has no attribute 'stide'

In [60]:
type(a)

torch.Tensor

In [57]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.stride()

(2, 1)

In [59]:
type(points)

torch.Tensor

In [61]:
points.is_contiguous()

True

In [62]:
points_t = points.t()

In [63]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [64]:
points_t.is_contiguous()

False

In [65]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [66]:
points_t.stride()

(1, 2)

In [67]:
points_t_cont = points_t.contiguous()

In [68]:
points_t_cont.stride()

(3, 1)

In [69]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]