In [13]:
import os, ssl
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and
getattr(ssl, '_create_unverified_context', None)):
    ssl._create_default_https_context = ssl._create_unverified_context

In [1]:
from torchvision import models

In [2]:
dir(models)

['AlexNet',
 'DenseNet',
 'GoogLeNet',
 'GoogLeNetOutputs',
 'Inception3',
 'InceptionOutputs',
 'MNASNet',
 'MobileNetV2',
 'ResNet',
 'ShuffleNetV2',
 'SqueezeNet',
 'VGG',
 '_GoogLeNetOutputs',
 '_InceptionOutputs',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_utils',
 'alexnet',
 'densenet',
 'densenet121',
 'densenet161',
 'densenet169',
 'densenet201',
 'detection',
 'googlenet',
 'inception',
 'inception_v3',
 'mnasnet',
 'mnasnet0_5',
 'mnasnet0_75',
 'mnasnet1_0',
 'mnasnet1_3',
 'mobilenet',
 'mobilenet_v2',
 'quantization',
 'resnet',
 'resnet101',
 'resnet152',
 'resnet18',
 'resnet34',
 'resnet50',
 'resnext101_32x8d',
 'resnext50_32x4d',
 'segmentation',
 'shufflenet_v2_x0_5',
 'shufflenet_v2_x1_0',
 'shufflenet_v2_x1_5',
 'shufflenet_v2_x2_0',
 'shufflenetv2',
 'squeezenet',
 'squeezenet1_0',
 'squeezenet1_1',
 'utils',
 'vgg',
 'vgg11',
 'vgg11_bn',
 'vgg13',
 'vgg13_bn',
 'vgg16',
 'vg

In [8]:
alex_model = models.AlexNet()

In [9]:
# alex_model

In [14]:
resnet = models.resnet101(pretrained=True)

Downloading: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth" to /Users/mnctty/.cache/torch/checkpoints/resnet101-5d3b4d8f.pth


In [15]:
resnet

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [17]:
from torchvision import transforms 

In [18]:
preprocess = transforms.Compose([transforms.Resize(256), transforms.CenterCrop(224), transforms.ToTensor(), transforms.Normalize(
mean=[0.485, 0.456, 0.406],
std=[0.229, 0.224, 0.225]
)])


In [19]:
from PIL import Image
img = Image.open("/Users/mnctty/Downloads/test-14-05-2021 2/_26_04_19_15311.jpg")

In [20]:
img.show()

In [37]:
img.size

(1600, 2000)

In [21]:
img_t = preprocess(img)

In [22]:
img_t.show()

AttributeError: 'Tensor' object has no attribute 'show'

In [30]:
img_t.shape

torch.Size([3, 224, 224])

In [23]:
import torch
batch_t = torch.unsqueeze(img_t, 0)

In [29]:
batch_t.shape

torch.Size([1, 3, 224, 224])

In [38]:
resnet.eval()

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [39]:
result = resnet(batch_t)

In [40]:
result

tensor([[-6.9345e-01, -4.1365e-01,  1.7459e+00, -2.2015e+00,  1.8892e+00,
         -1.6425e+00, -2.3469e+00, -6.5436e-01, -4.8945e+00, -3.2912e+00,
         -3.3817e+00, -1.4752e+00, -3.4436e+00, -3.2714e+00, -2.5629e+00,
         -2.6656e+00, -2.6404e+00, -4.0256e+00, -2.9089e+00, -2.4099e+00,
         -1.7498e+00, -2.2959e+00, -1.3604e+00, -3.4180e+00, -3.5521e+00,
         -4.5558e+00, -2.6236e+00, -2.4881e+00, -2.2477e+00, -2.5244e+00,
         -1.3242e+00,  7.1809e-01, -6.5287e-01,  4.6586e-01,  1.2912e+00,
         -2.6094e+00,  1.0679e+00, -1.5019e+00, -1.0283e+00, -3.5343e-01,
          1.9773e+00, -1.9953e+00, -1.8665e+00, -1.4774e-01, -5.5193e-01,
         -1.9977e+00,  1.4395e+00, -1.7543e+00, -1.9807e+00,  1.9187e-01,
          1.5565e+00,  7.9920e-01, -4.7467e-02, -2.7894e+00, -2.2497e+00,
          7.9981e-01, -3.3455e+00, -1.5628e+00, -1.5866e+00,  1.1214e+00,
          5.0279e-01,  1.5519e-01, -2.3180e-01, -1.6289e+00, -9.9496e-03,
         -1.1145e+00, -2.2470e+00, -9.

In [41]:
result.shape

torch.Size([1, 1000])

In [42]:
with open('/Users/mnctty/Desktop/DL with Pytorch/1_lessons/imagenet_classes_list.txt') as f:
    labels = [line.strip() for line in f.readlines()]

In [43]:
labels

['tench, Tinca tinca',
 'goldfish, Carassius auratus',
 'great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias',
 'tiger shark, Galeocerdo cuvieri',
 'hammerhead, hammerhead shark',
 'electric ray, crampfish, numbfish, torpedo',
 'stingray',
 'cock',
 'hen',
 'ostrich, Struthio camelus',
 'brambling, Fringilla montifringilla',
 'goldfinch, Carduelis carduelis',
 'house finch, linnet, Carpodacus mexicanus',
 'junco, snowbird',
 'indigo bunting, indigo finch, indigo bird, Passerina cyanea',
 'robin, American robin, Turdus migratorius',
 'bulbul',
 'jay',
 'magpie',
 'chickadee',
 'water ouzel, dipper',
 'kite',
 'bald eagle, American eagle, Haliaeetus leucocephalus',
 'vulture',
 'great grey owl, great gray owl, Strix nebulosa',
 'European fire salamander, Salamandra salamandra',
 'common newt, Triturus vulgaris',
 'eft',
 'spotted salamander, Ambystoma maculatum',
 'axolotl, mud puppy, Ambystoma mexicanum',
 'bullfrog, Rana catesbeiana',
 'tree frog, tree-f

In [44]:
_, index = torch.max(result, 1)

In [45]:
index

tensor([610])

In [46]:
_

tensor([10.3286], grad_fn=<MaxBackward0>)

In [51]:
percentage = torch.nn.functional.softmax(result, dim=1)[0] * 100

In [52]:
percentage

tensor([4.6618e-04, 6.1670e-04, 5.3451e-03, 1.0319e-04, 6.1684e-03, 1.8047e-04,
        8.9219e-05, 4.8477e-04, 6.9834e-06, 3.4703e-05, 3.1701e-05, 2.1332e-04,
        2.9798e-05, 3.5397e-05, 7.1888e-05, 6.4874e-05, 6.6526e-05, 1.6650e-05,
        5.0861e-05, 8.3779e-05, 1.6210e-04, 9.3893e-05, 2.3927e-04, 3.0571e-05,
        2.6734e-05, 9.7984e-06, 6.7659e-05, 7.7470e-05, 9.8528e-05, 7.4711e-05,
        2.4811e-04, 1.9124e-03, 4.8549e-04, 1.4861e-03, 3.3923e-03, 6.8623e-05,
        2.7133e-03, 2.0771e-04, 3.3352e-04, 6.5498e-04, 6.7367e-03, 1.2681e-04,
        1.4425e-04, 8.0456e-04, 5.3706e-04, 1.2652e-04, 3.9346e-03, 1.6137e-04,
        1.2868e-04, 1.1299e-03, 4.4228e-03, 2.0740e-03, 8.8942e-04, 5.7317e-05,
        9.8331e-05, 2.0753e-03, 3.2870e-05, 1.9544e-04, 1.9083e-04, 2.8624e-03,
        1.5420e-03, 1.0892e-03, 7.3969e-04, 1.8293e-04, 9.2342e-04, 3.0599e-04,
        9.8596e-05, 3.4929e-04, 3.8431e-05, 5.1405e-04, 4.1456e-05, 2.2957e-03,
        8.0100e-05, 3.0465e-04, 7.7281e-

In [53]:
percentage.shape

torch.Size([1000])

In [54]:
labels[index[0]], percentage[index[0]].item()

('jersey, T-shirt, tee shirt', 28.535076141357422)

In [56]:
_, indices = torch.sort(result, descending=True)

In [57]:
[(labels[idx], percentage[idx].item()) for idx in indices[0][:5]]

[('jersey, T-shirt, tee shirt', 28.535076141357422),
 ('racket, racquet', 26.31031608581543),
 ('miniskirt, mini', 13.488390922546387),
 ('tennis ball', 6.2823405265808105),
 ('sweatshirt', 3.5871732234954834)]